# SPDX-License-Identifier: Apache-2.0
# K9-AIF Framework
"""Phase and milestone facts (DoDI 5000.85 3.5-3.10) every DAS agent that drafts or judges a package
gets in its prompt. Found necessary on the real model: without them it called Milestone A the start
of EMD and spoke of "the Milestone A (MSA) phase" (a decision is not a phase)."""

PROCESS_FACTS = (
    "Process facts (Major Capability Acquisition, DoDI 5000.85):\n"
    "- Materiel Development Decision (MDD): the mandatory entry point. The MDA decides the phase of entry\n"
    "  (normally Materiel Solution Analysis, MSA) and the initial review milestone (normally Milestone A),\n"
    "  documented in an ADM with the approved AoA study guidance and study plan attached.\n"
    "- MSA: the AoA is conducted; the lead Service or Component, with the requirements and acquisition\n"
    "  communities, selects the preferred materiel solution (SE Guidebook 3.1); MSA ends at Milestone A.\n"
    "- Milestone A: approves entry into Technology Maturation and Risk Reduction (TMRR), the acquisition\n"
    "  strategy (including its pathway) and release of the final RFP for TMRR.\n"
    "- TMRR: critical technologies are matured and risk reduced here (competitive prototyping where\n"
    "  planned), with the System Requirements Review, CDD-equivalent validation and PDR. A strategy\n"
    "  approved at Milestone A plans and contracts for TMRR.\n"
    "- Development RFP Release decision point (end of TMRR, before Milestone B): approves release of the\n"
    "  solicitation for EMD. The EMD contract is awarded after Milestone B.\n"
    "- Milestone B: approves entry into Engineering and Manufacturing Development (EMD).\n"
    "  Milestone C: Production and Deployment. Never attribute EMD to Milestone A.\n"
    "- A milestone is a decision point, not a phase: say \"MSA phase\", \"at Milestone A\".\n"
    "- The System Requirements Review takes place during TMRR, after Milestone A: an SRR gap affects\n"
    "  proceeding through TMRR toward Milestone B, never entering TMRR.\n"
    "- Major Capability Acquisition is a pathway, not a program category: a program on it is an MDAP\n"
    "  only if its ACAT (set by statutory dollar thresholds and MDA designation) makes it one. If the\n"
    "  source gives no ACAT, say so and treat MDAP-only requirements as applying only if it is ACAT I;\n"
    "  never state or estimate the MDAP dollar thresholds, and never cite a DoD issuance for them.\n"
    "- The Milestone A technology certification for MDAPs is 10 U.S.C. 4251 (formerly 10 U.S.C. 2366a).\n"
    "\n"
    "The five gates, in order (judge a gate only as what it is; its id is in the input as gate_id):\n"
    "- SERVICE-VALIDATION: the Service requirements board validates the Service's capability requirement\n"
    "  under the Joint Force Requirements Process (CJCSI 5123.01J, CJCSM 5123.01A), which replaced JCIDS.\n"
    "  It is a requirements decision, not an acquisition milestone: it comes before the MDD, and approval\n"
    "  starts the MDD package. Never call it Milestone A entry or TMRR entry, and never cite DoDI 5000.85\n"
    "  as its authority.\n"
    "- JCI-REVIEW: the Joint Capability Integration review by the JROC, JCB or FCB the Joint Staffing\n"
    "  Designator names (CJCSM 5123.01A). It runs in parallel and never holds the acquisition flow.\n"
    "- MDD: the Milestone Decision Authority's Materiel Development Decision (DoDI 5000.85).\n"
    "- MILESTONE-A: the MDA approves TMRR entry and the acquisition strategy (DoDI 5000.85).\n"
    "- SE-REVIEW-SRR: the System Requirements Review during TMRR, decided by the technical review chair\n"
    "  (DoD SE Guidebook); a step toward Milestone B, not a milestone.\n"
)
