# SPDX-License-Identifier: Apache-2.0
# K9-AIF Framework
"""Draw the DAS job flow from the process model (config/process_model.yaml).

Writes src/k9_dow/api/static/das-hil-flow.svg (light; the paper figure) and
das-hil-flow-dark.svg (das.k9x.ai). Re-run after any change to the process model:

    PYTHONPATH=src python tools/flow_diagram.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from k9_dow.config.process_model import load_process_model  # noqa: E402

THEMES = {
    "light": dict(bg="#ffffff", text="#1f2937", sub="#4b5563", line="#6b7280",
                  das_fill="#eef4ff", das_line="#2563eb", hil_fill="#ecfdf5", hil_line="#059669",
                  in_fill="#f5f3ff", in_line="#7c3aed", par_fill="#fffbeb", par_line="#d97706"),
    "dark": dict(bg="#111a2e", text="#d3dae6", sub="#aab5c8", line="#7d889c",
                 das_fill="#16264a", das_line="#6b9cf5", hil_fill="#10302a", hil_line="#34d399",
                 in_fill="#241a40", in_line="#a78bfa", par_fill="#33270f", par_line="#fbbf24"),
}

W, H = 1000, 420
BW, BH = 150, 74

# (key, system, title, subtitle lines)
def boxes(pm):
    g = pm.gates
    return [
        ("in", "DAS", "Upload", ["Docling: PDF, Word,", "scans → Markdown (OCR)"]),
        ("scr", "DAS", "Screening", ["Shield + Guardian;", "warnings report"]),
        ("req", "DAS", "Requirement", ["Service format,", "views, JSD proposal"]),
        ("sv", "K9X HIL", "Service validation", ["Service requirements", "board"]),
        ("mddp", "DAS", "MDD package", ["AoA study guidance", "and study plan"]),
        ("mdd", "K9X HIL", "MDD", ["MDA: phase of entry"]),
        ("msa", "DAS", "MSA → MS A package", ["AoA summary, ASR,", "acquisition strategy"]),
        ("msA", "K9X HIL", "Milestone A", ["MDA: strategy,", "pathway, TMRR entry"]),
        ("tmrr", "DAS", "TMRR: SRR package", ["system requirements,", "traceability"]),
        ("srr", "K9X HIL", "SRR", ["technical review chair"]),
    ]


def render(theme: str) -> str:
    c = THEMES[theme]
    pm = load_process_model()
    bx = boxes(pm)
    # Row 1: five boxes left→right; row 2: five boxes left→right.
    xs = [20 + i * 196 for i in range(5)]
    pos = {}
    for i, b in enumerate(bx):
        row, col = divmod(i, 5)
        pos[b[0]] = (xs[col], 60 + row * 196)
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" '
           f'font-family="Helvetica, Arial, sans-serif">',
           f"  <!-- DAS job flow, process model {pm.id} (as of {pm.as_of}). Generated by tools/flow_diagram.py "
           f"from config/process_model.yaml; do not edit by hand. -->",
           "  <defs>",
           f'    <marker id="a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto">'
           f'<path d="M0,0 L10,5 L0,10 z" fill="{c["line"]}"/></marker>',
           f'    <marker id="p" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto">'
           f'<path d="M0,0 L10,5 L0,10 z" fill="{c["par_line"]}"/></marker>',
           "  </defs>",
           f'  <rect width="{W}" height="{H}" fill="{c["bg"]}"/>',
           f'  <text x="20" y="28" font-size="14" font-weight="700" fill="{c["text"]}">'
           f'{pm.pathway_title}: requirement to Milestone A and the SRR</text>',
           f'  <text x="{W - 20}" y="28" font-size="12" text-anchor="end" fill="{c["sub"]}">'
           f'process model {pm.id} · current as of {pm.as_of}</text>']
    n = 0
    for key, system, title, subs in bx:
        x, y = pos[key]
        hil = system == "K9X HIL"
        fill, line = ((c["hil_fill"], c["hil_line"]) if hil else
                      (c["in_fill"], c["in_line"]) if key in ("in", "scr") else (c["das_fill"], c["das_line"]))
        n += 1
        out.append(f'  <rect x="{x}" y="{y}" width="{BW}" height="{BH}" rx="6" fill="{fill}" stroke="{line}" stroke-width="1.5"/>')
        out.append(f'  <text x="{x + 8}" y="{y + 15}" font-size="10.5" font-weight="700" fill="{line}">{n} · {system}</text>')
        out.append(f'  <text x="{x + BW / 2}" y="{y + 35}" font-size="13" font-weight="700" text-anchor="middle" fill="{c["text"]}">{title}</text>')
        for j, s in enumerate(subs):
            out.append(f'  <text x="{x + BW / 2}" y="{y + 51 + j * 13}" font-size="10.5" text-anchor="middle" fill="{c["sub"]}">{s}</text>')

    def arrow(a, b, label=""):
        (x1, y1), (x2, y2) = pos[a], pos[b]
        if y1 == y2:
            out.append(f'  <line x1="{x1 + BW}" y1="{y1 + BH / 2}" x2="{x2 - 3}" y2="{y2 + BH / 2}" '
                       f'stroke="{c["line"]}" stroke-width="1.4" marker-end="url(#a)"/>')
            if label:
                out.append(f'  <text x="{(x1 + BW + x2) / 2}" y="{y1 + BH / 2 - 6}" font-size="10" text-anchor="middle" fill="{c["sub"]}">{label}</text>')
        else:   # end of row 1 → start of row 2
            mid = y2 - 24
            out.append(f'  <path d="M{x1 + BW / 2},{y1 + BH} V{mid} H{x2 + BW / 2} V{y2 - 3}" fill="none" '
                       f'stroke="{c["line"]}" stroke-width="1.4" marker-end="url(#a)"/>')
            if label:
                out.append(f'  <text x="{(x1 + x2 + BW) / 2}" y="{mid - 6}" font-size="10" text-anchor="middle" fill="{c["sub"]}">{label}</text>')

    seq = [b[0] for b in bx]
    for a, b in zip(seq, seq[1:]):
        arrow(a, b, "approve" if a in ("sv", "mdd", "msA") else "")

    # JCI review: parallel to the flow, never blocking, from Service validation
    x, y = pos["sv"]
    jx, jy = x + 3, y + BH + 22
    out.append(f'  <path d="M{x + BW / 2},{y + BH} V{jy - 3}" stroke="{c["par_line"]}" stroke-width="1.4" '
               f'stroke-dasharray="5 3" fill="none" marker-end="url(#p)"/>')
    out.append(f'  <rect x="{jx}" y="{jy}" width="{BW - 6}" height="34" rx="6" fill="{c["par_fill"]}" stroke="{c["par_line"]}" stroke-width="1.3"/>')
    out.append(f'  <text x="{jx + (BW - 6) / 2}" y="{jy + 14}" font-size="11" font-weight="700" text-anchor="middle" fill="{c["text"]}">K9X HIL · JCI review</text>')
    out.append(f'  <text x="{jx + (BW - 6) / 2}" y="{jy + 27}" font-size="10" text-anchor="middle" fill="{c["sub"]}">parallel, never blocks</text>')
    # SRR end
    x, y = pos["srr"]
    out.append(f'  <text x="{x + BW / 2}" y="{y + BH + 18}" font-size="10.5" text-anchor="middle" fill="{c["sub"]}">approve → built flow ends</text>')
    out.append(f'  <text x="20" y="{H - 14}" font-size="10.5" fill="{c["sub"]}">After each approval the DAS admin starts the next run. '
               f'Designed, not built: SFR, PDR, CDD-equivalent validation, Development RFP Release, Milestone B, other pathways.</text>')
    out.append("</svg>")
    return "\n".join(out) + "\n"


def main():
    static = ROOT / "src" / "k9_dow" / "api" / "static"
    (static / "das-hil-flow.svg").write_text(render("light"), encoding="utf-8")
    (static / "das-hil-flow-dark.svg").write_text(render("dark"), encoding="utf-8")
    print("wrote", static / "das-hil-flow.svg", "and das-hil-flow-dark.svg")


if __name__ == "__main__":
    main()
